### ISSUE TITLE
Does experimental dataset's metadat_files available?

### ISSUE THREAD

**Issue by zhanh-he** [anusfoil/SymRep#4]
Hi, thanks for providing codes and I am current investigating (used it as baseline). My repeat experiments results are a bit away the paper's, and likely due to my composers split difference. Would it possible to provide your metadata.csv files?

In the conf, they are:
```
  ASAP:
    dataset_dir: /homes/hz009/Research/Datasets/asap-dataset/
    metadata_file: /homes/hz009/Research/Datasets/asap-dataset/metadata-v1.3.csv <---

  ATEPP: 
    dataset_dir: /homes/hz009/Research/Datasets/ATEPP-1.1/
    metadata_file: /homes/hz009/Research/Datasets/ATEPP-1.1/ATEPP-metadata-1.5.csv <---
```
